#!/usr/bin/env node

var sys = require('sys')
var exec = require('child_process').exec;
//function puts(error, stdout, stderr) { sys.puts(stdout); console.log(error); console.log(stderr); }
function puts(error, stdout, stderr) { console.log(error) }
var Settings = require('../Settings')

var egg = {
  "devices": ["0x8000", "0x8001"],
  "address": "60:c5:47:04:f1:94"
}

var cmd = 'curl -XPOST ' + Settings.Queen.URL + '/egg/new -H "Content-Type: Application/json" -d \'' + JSON.stringify(egg) + '\'; \n'

console.log(cmd)
exec(cmd, puts)
