#!/usr/bin/env node

var program = require('commander');
var sys = require('sys')
var exec = require('child_process').exec;
function puts(error, stdout, stderr) { sys.puts(stdout) }
var cmd = ''
var Settings = require('../Settings')
var sensorDefs = require('./sensorDefs.js')
var request = require('request')

program
  .version('0.0.1')
  .option('-c, --server', '', '')
  .parse(process.argv);

var server = (program.server) 
  ? program.server
  : Settings.CouchDB.URL

// @todo Get sensors in config database


request(server + '/config/_all_docs?include_docs=true', function (error, response, body) {
  if (response.statusCode == "404") {
    console.log('Cannot find config database')
  }
  else {
    var data = JSON.parse(body)

    data.rows.forEach(function(row) {
      if (row.doc.kind == 'sensor') {
        cmd += 'curl -XDELETE ' + server + '/' + row.id + '; \n'
      }
    })

    cmd += 'curl -XDELETE ' + server + '/config' + '; \n'

    console.log(cmd)
    exec(cmd, puts)
  }
})
